export const BOBBINS = [
    { value: 1, name: 'Vị trí số 1' },
    { value: 2, name: 'Vị trí số 2' },
    { value: 3, name: 'Vị trí số 3' },
    { value: 4, name: 'Vị trí số 4' },
    { value: 5, name: 'Vị trí số 5' },
    { value: 6, name: 'Vị trí số 6' },
    { value: 7, name: 'Vị trí số 7' },
    { value: 8, name: 'Vị trí số 8' },
    { value: 9, name: 'Vị trí số 9' },
    { value: 10, name: 'Vị trí số 10' },
    { value: 11, name: 'Vị trí số 11' },
    { value: 12, name: 'Vị trí số 12' },
    { value: 13, name: 'Vị trí số 13' },
    { value: 14, name: 'Vị trí số 14' },
    { value: 15, name: 'Vị trí số 15' },
    { value: 16, name: 'Vị trí số 16' },
    { value: 17, name: 'Vị trí số 17' },
    { value: 18, name: 'Vị trí số 18' },
    { value: 19, name: 'Vị trí số 19' },
    { value: 20, name: 'Vị trí số 20' },
    { value: 21, name: 'Vị trí số 21' },
    { value: 22, name: 'Vị trí số 22' },
    { value: 23, name: 'Vị trí số 23' },
    { value: 24, name: 'Vị trí số 24' },
]